// src/constants/locationData.js

// Danh sách các tỉnh/thành
export const provinces = [
    { value: "An Giang", label: "An Giang" },
    { value: "Ba Ria Vung Tau", label: "Bà Rịa - Vũng Tàu" },
    { value: "Bac Giang", label: "Bắc Giang" },
    { value: "Bac Lieu", label: "Bạc Liêu" },
    { value: "Bac Ninh", label: "Bắc Ninh" },
    { value: "Ben Tre", label: "Bến Tre" },
    { value: "Binh Dinh", label: "Bình Định" },
    { value: "Binh Duong", label: "Bình Dương" },
    { value: "Binh Phuoc", label: "Bình Phước" },
    { value: "Binh Thuan", label: "Bình Thuận" },
    { value: "Ca Mau", label: "Cà Mau" },
    { value: "Can Tho", label: "Cần Thơ" },
    { value: "Da Nang", label: "Đà Nẵng" },
    { value: "Dak Lak", label: "Đắk Lắk" },
    { value: "Dong Nai", label: "Đồng Nai" },
    { value: "Dong Thap", label: "Đồng Tháp" },
    { value: "Gia Lai", label: "Gia Lai" },
    { value: "Ha Noi", label: "Hà Nội" },
    { value: "Hai Duong", label: "Hải Dương" },
    { value: "Hai Phong", label: "Hải Phòng" },
    { value: "Hau Giang", label: "Hậu Giang" },
    { value: "Ho Chi Minh City", label: "TP. Hồ Chí Minh" },
    { value: "Hung Yen", label: "Hưng Yên" },
    { value: "Khanh Hoa", label: "Khánh Hòa" },
    { value: "Kien Giang", label: "Kiên Giang" },
    { value: "Lam Dong", label: "Lâm Đồng" },
    { value: "Long An", label: "Long An" },
    { value: "Nghe An", label: "Nghệ An" },
    { value: "Quang Nam", label: "Quảng Nam" },
    { value: "Quang Ngai", label: "Quảng Ngãi" },
    { value: "Soc Trang", label: "Sóc Trăng" },
    { value: "Tay Ninh", label: "Tây Ninh" },
    { value: "Thai Binh", label: "Thái Bình" },
    { value: "Thanh Hoa", label: "Thanh Hóa" },
    { value: "Thua Thien Hue", label: "Thừa Thiên Huế" },
    { value: "Tien Giang", label: "Tiền Giang" },
    { value: "Tra Vinh", label: "Trà Vinh" },
    { value: "Vinh Long", label: "Vĩnh Long" },
    { value: "Vinh Phuc", label: "Vĩnh Phúc" }
];

// Danh sách quận/huyện theo tỉnh
export const districtMap = {
    "An Giang": [
        { value: "HChauPhu", label: "Huyện Châu Phú" },
        { value: "TpChauDoc", label: "Thành phố Châu Đốc" },
        { value: "TpLongXuyen", label: "Thành phố Long Xuyên" },
    ],
    "Ba Ria Vung Tau": [
        { value: "HChauDuc", label: "Huyện Châu Đức" },
        { value: "HDatDo", label: "Huyện Đất Đỏ" },
        { value: "HLongDien", label: "Huyện Long Điền" },
        { value: "HXuyenMoc", label: "Huyện Xuyên Mộc" },
        { value: "TpBaRia", label: "Thành phố Bà Rịa" },
        { value: "TpVungTau", label: "Thành phố Vũng Tàu" },
        { value: "TxPhuMy", label: "Thị xã Phú Mỹ" },
    ],
    "Bac Giang": [
        { value: "TpBacGiang", label: "Thành phố Bắc Giang" },
    ],
    "Bac Lieu": [
        { value: "HHoaBinh", label: "Huyện Hòa Bình" },
        { value: "TpBacLieu", label: "Thành phố Bạc Liêu" },
    ],
    "Bac Ninh": [
        { value: "TpBacNinh", label: "Thành phố Bắc Ninh" },
        { value: "TxTuSon", label: "Thị xã Từ Sơn" },
    ],
    "Ben Tre": [
        { value: "HBaTri", label: "Huyện Ba Tri" },
        { value: "TpBenTre", label: "Thành phố Bến Tre" },
    ],
    "Binh Dinh": [
        { value: "QTPhu", label: "Huyện Phù Cát" }, 
        { value: "TpQuyNhon", label: "Thành phố Quy Nhơn" },
    ],
    "Binh Duong": [
        { value: "TpThuanAn", label: "Thành phố Thuận An" },
        { value: "TpThuDauMot", label: "Thành phố Thủ Dầu Một" },
        { value: "TxBenCat", label: "Thị xã Bến Cát" },
        { value: "TxDiAn", label: "Thị xã Dĩ An" },
    ],
    "Binh Phuoc": [
        { value: "TpDongXoai", label: "Thành phố Đồng Xoài" },
        { value: "TxPhuocLong", label: "Thị xã Phước Long" },
    ],
    "Binh Thuan": [
        { value: "TpPhanThiet", label: "Thành phố Phan Thiết" },
        { value: "TxLaGi", label: "Thị xã La Gi" },
    ],
    "Ca Mau": [
        { value: "HCaiNuoc", label: "Huyện Cái Nước" },
        { value: "TpCaMau", label: "Thành phố Cà Mau" },
    ],
    "Can Tho": [
        { value: "HThoiLai", label: "Huyện Thới Lai" },
        { value: "QBinhThuy", label: "Quận Bình Thủy" },
        { value: "QCaiRang", label: "Quận Cái Răng" },
        { value: "QNinhKieu", label: "Quận Ninh Kiều" },
        { value: "QThotNot", label: "Quận Thốt Nốt" },
    ],
    "Da Nang": [
        { value: "HHoaVang", label: "Huyện Hòa Vang" },
        { value: "QCamLe", label: "Quận Cẩm Lệ" },
        { value: "QHaiChau", label: "Quận Hải Châu" },
        { value: "QLienChieu", label: "Quận Liên Chiểu" },
        { value: "QNguHanhSon", label: "Quận Ngũ Hành Sơn" },
        { value: "QSonTra", label: "Quận Sơn Trà" },
        { value: "QThanhKhe", label: "Quận Thanh Khê" },
    ],
    "Dak Lak": [
        { value: "TpBuonMaThuot", label: "Thành phố Buôn Ma Thuột" },
        { value: "TxBuonHo", label: "Thị xã Buôn Hồ" },
    ],
    "Dong Nai": [
        { value: "HLongThanh", label: "Huyện Long Thành" },
        { value: "HNhonTrach", label: "Huyện Nhơn Trạch" },
        { value: "HTrangBom", label: "Huyện Trảng Bom" },
        { value: "HVinhCuu", label: "Huyện Vĩnh Cửu" },
        { value: "TpBienHoa", label: "Thành phố Biên Hòa" },
        { value: "TpGoCong", label: "Thành phố Gò Công" },
        { value: "TxLongKhanh", label: "Thị xã Long Khánh" },
    ],
    "Dong Thap": [
        { value: "TpCaoLanh", label: "Thành phố Cao Lãnh" },
        { value: "TpSaDec", label: "Thành phố Sa Đéc" },
    ],
    "Gia Lai": [
        { value: "TpPleiku", label: "Thành phố Pleiku" },
    ],
    "Ha Noi": [
        { value: "HDongAnh", label: "Huyện Đông Anh" },
        { value: "HGiaLam", label: "Huyện Gia Lâm" },
        { value: "HHoaiDuc", label: "Huyện Hoài Đức" },
        { value: "HThanhOai", label: "Huyện Thanh Oai" },
        { value: "HThanhTri", label: "Huyện Thanh Trì" },
        { value: "QBacTuLiem", label: "Quận Bắc Từ Liêm" },
        { value: "QBaDinh", label: "Quận Ba Đình" },
        { value: "QCauGiay", label: "Quận Cầu Giấy" },
        { value: "QDongDa", label: "Quận Đống Đa" },
        { value: "QHaDong", label: "Quận Hà Đông" },
        { value: "QHaiBaTrung", label: "Quận Hai Bà Trưng" },
        { value: "QHoangMai", label: "Quận Hoàng Mai" },
        { value: "QHoanKiem", label: "Quận Hoàn Kiếm" },
        { value: "QLongBien", label: "Quận Long Biên" },
        { value: "QNamTuLiem", label: "Quận Nam Từ Liêm" },
        { value: "QTayHo", label: "Quận Tây Hồ" },
        { value: "QThanhTri", label: "Quận Thanh Trì" },
        { value: "QThanhXuan", label: "Quận Thanh Xuân" },
    ],
    "Hai Duong": [
        { value: "TpHaiDuong", label: "Thành phố Hải Dương" },
        { value: "TpThaiBinh", label: "Thành phố Thái Bình" },
    ],
    "Hai Phong": [
        { value: "HThuyNguyen", label: "Huyện Thủy Nguyên" },
        { value: "QDoSon", label: "Quận Đồ Sơn" },
        { value: "QHaiAn", label: "Quận Hải An" },
        { value: "QHongBang", label: "Quận Hồng Bàng" },
        { value: "QLeChan", label: "Quận Lê Chân" },
        { value: "QNgoQuyen", label: "Quận Ngô Quyền" },
    ],
    "Hau Giang": [
        { value: "TpViThanh", label: "Thành phố Vị Thanh" },
        { value: "TxNgaBay", label: "Thị xã Ngã Bảy" },
    ],
    "Ho Chi Minh City": [
        { value: "HBinhChanh", label: "Huyện Bình Chánh" },
        { value: "HCuChi", label: "Huyện Củ Chi" },
        { value: "HHocMon", label: "Huyện Hóc Môn" },
        { value: "HNhaBe", label: "Huyện Nhà Bè" },
        { value: "PCatLai", label: "Phường Cát Lái" },
        { value: "PHiepBinh", label: "Phường Hiệp Bình" },
        { value: "PThongTayHoi", label: "Phường Thống Nhất" },
        { value: "Q1", label: "Quận 1" },
        { value: "Q2", label: "Quận 2" },
        { value: "Q3", label: "Quận 3" },
        { value: "Q4", label: "Quận 4" },
        { value: "Q5", label: "Quận 5" },
        { value: "Q6", label: "Quận 6" },
        { value: "Q7", label: "Quận 7" },
        { value: "Q8", label: "Quận 8" },
        { value: "Q9", label: "Quận 9" },
        { value: "Q10", label: "Quận 10" },
        { value: "Q11", label: "Quận 11" },
        { value: "Q12", label: "Quận 12" },
        { value: "QTanBinh", label: "Quận Tân Bình" },
        { value: "QTanPhu", label: "Quận Tân Phú" },
        { value: "QThuDuc", label: "Quận Thủ Đức" },
        { value: "QBinhTan", label: "Quận Bình Tân" },
        { value: "QBinhThanh", label: "Quận Bình Thạnh" },
        { value: "QGoVap", label: "Quận Gò Vấp" },
        { value: "QPhuNhuan", label: "Quận Phú Nhuận" },
    ],
    "Hung Yen": [
        { value: "HVanGiang", label: "Huyện Văn Giang" },
        { value: "TpHungYen", label: "Thành phố Hưng Yên" },
    ],
    "Khanh Hoa": [
        { value: "TpNhaTrang", label: "Thành phố Nha Trang" },
    ],
    "Kien Giang": [
        { value: "HAnBien", label: "Huyện An Biên" },
        { value: "TpRachGia", label: "Thành phố Rạch Giá" },
    ],
    "Lam Dong": [
        { value: "HDucTrong", label: "Huyện Đức Trọng" },
        { value: "HLamHa", label: "Huyện Lâm Hà" },
        { value: "TpBaoLoc", label: "Thành phố Bảo Lộc" },
        { value: "TpDaLat", label: "Thành phố Đà Lạt" },
    ],
    "Long An": [
        { value: "HBenLuc", label: "Huyện Bến Lức" },
        { value: "HCanGiuoc", label: "Huyện Cần Giuộc" },
        { value: "HChauThanh", label: "Huyện Châu Thành" },
        { value: "HDucHoa", label: "Huyện Đức Hòa" },
        { value: "TpTanAn", label: "Thành phố Tân An" },
    ],
    "Nghe An": [
        { value: "TpVinh", label: "Thành phố Vinh" },
    ],
    "Quang Nam": [
        { value: "TpHoiAn", label: "Thành phố Hội An" },
        { value: "TpTamKy", label: "Thành phố Tam Kỳ" },
    ],
    "Quang Ngai": [
        { value: "TpQuangNgai", label: "Thành phố Quảng Ngãi" },
    ],
    "Soc Trang": [
        { value: "TpSocTrang", label: "Thành phố Sóc Trăng" },
    ],
    "Tay Ninh": [
        { value: "HHoaThanh", label: "Huyện Hòa Thành" },
        { value: "TpTayNinh", label: "Thành phố Tây Ninh" },
    ],
    "Thai Binh": [
        { value: "HThaiThuy", label: "Huyện Thái Thụy" },
        { value: "TpThaiBinh", label: "Thành phố Thái Bình" },
    ],
    "Thanh Hoa": [
        { value: "TpThanhHoa", label: "Thành phố Thanh Hóa" },
    ],
    "Thua Thien Hue": [
        { value: "TpHue", label: "Thành phố Huế" },
    ],
    "Tien Giang": [
        { value: "HChoGao", label: "Huyện Chợ Gạo" },
        { value: "TpMyTho", label: "Thành phố Mỹ Tho" },
        { value: "TxCaiLay", label: "Thị xã Cai Lậy" },
        { value: "TxGoCong", label: "Thị xã Gò Công" },
    ],
    "Tra Vinh": [
        { value: "HCangLong", label: "Huyện Càng Long" },
        { value: "HTieuCan", label: "Huyện Tiểu Cần" },
    ],
    "Vinh Long": [
        { value: "TpVinhLong", label: "Thành phố Vĩnh Long" },
    ],
    "Vinh Phuc": [
        { value: "TpVinhYen", label: "Thành phố Vĩnh Yên" },
    ],
};